on:
  push:
    branches:
      - main

jobs:
  apply:
    uses: 1ndistinct/ops/.github/workflows/terragrunt-apply-workflow.yaml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}