on:
  push:
    branches:
      - main

env:
  tf_version: '1.4.5'
  tg_version: '0.54.22'
  working_dir: './aws/staging/eu-west-2'

jobs:
  apply:
    uses: 1ndistinct/ops/.github/workflows/terragrunt-apply-workflow.yaml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.STAGING_AWS_REGION }}